version: '{build}'
clone_folder: C:\gopath\src\github.com\spf13\afero
environment:
  GOPATH: C:\gopath
build_script:
- cmd: >-
    go version

    go env

    go get -v github.com/parro-it/afero/...

    go build github.com/parro-it/afero
test_script:
- cmd: go test -race -v github.com/parro-it/afero/...
