version: "{build}"
clone_folder: C:\gopath\src\github.com\spf13\afero
environment:
  GOPATH: C:\gopath
build_script:
  - cmd: >-
      go version

      go env

      go get -v github.com/meteocima/afero/...

      go build -v github.com/meteocima/afero/...
test_script:
  - cmd: go test -count=1 -cover -race -v github.com/meteocima/afero/...
